name: bilanga

services:

  postgres:
    image: postgres:17
    container_name: bilanga_dev_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dev_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '55820:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: bilanga-dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "45210:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin


  redis:
    image: 'redis:8.0.0'
    container_name: redis_bilanga
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: bilanga-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  esdata:
  dev_db_data:
  pgadmin_data:
  redis-data:
  minio-data:


